= nixconfig

Nixos config for my machines using flakes.

Honest to God I cannot tell you how it works (as per usual with nix or nixos).
I coded it while being possessed so here it is. Probably it is usable.

== Install

To install this flake from an installation iso, first enter a `sudo` mode and then create a Nix shell with dependencies:

```sh
$ sudo -i
# nix-shell -p git nixVersions.latest
```

This is required since *git* isn't a hard dependency, and flakes only available in latest *nix*.

Then, partition according to the https://nixos.org/manual/nixos/stable/#sec-installation-manual-partitioning[NixOS manual].
In this nixconfig, there is an option to create and automatically link directories from `/storage` to `/home/user`, so it might be usefull to mount `/` to hdd and home directory to ssd.

After that, mount disks and run the actual installation:

```sh
# mount /dev/disk/by-label/nixos /mnt
# mkdir -p /mnt/boot
# mount /dev/disk/by-label/boot /mnt/boot
# nixos-install --root /mnt --flake .#hostname
```

NOTE: `.#hostname` should be a valid host in _hosts/_.

== Adding a new host

To add a new host, first you need to create a host dir in _hosts/_, and then generate a hadrware config:

```sh
# mkdir hosts/myhost
# nixos-generate-config --root /mnt --show-hardware-config > hosts/myhost/hardware.nix
```

Hardware config must be named _hardware.nix_. Then add or copy a `system.nix` file and config a new host system. 

NOTE: Be sure to check out https://github.com/NixOS/nixos-hardware[nixos-hardware] for more info about specific hardware !

=== Set background

Background management is made with `background` command (which is a shortcut to `setroot --store`). Why though ? Eh.

To see available options and usage, consult `man setroot` (but since *setroot* is not included in environemnt packanges: `nix shell nixpkgs#setroot -c "man setroot"`).
In general, you just want to simply set background pictures:

```sh
$ background pictures/wallpapers/left-monitor-picture.png \
             pictures/wallpapers/right-monitor-picture.png
```

Every run of `background` command is saved so it would be restored at the next system start (via `onStartupScript`).

== Future work
* Unclutter home
* Audio change notification
* Pick window & audio change it + notification
* Move to miri (wayland gogogo)
