= nixconfig

big wip

== TODO
* [x] Dunst notifications (or something else)  and plug notifications to events
* [x] Transmission and its events
* [x] Alacritty module
* [ ] Unclutter home
* [ ] Droidcam module
* [x] Remove all 'with lib;'
* [ ] Declarative pretty config: colors and background image(s)
* [x] Zsh with simple prompt
* [ ] System update event & prograss bar (if possible) notification
* [ ] Audio change notification
* [ ] Pick window & audio change it + notification
* [ ] Polybar

== Pile of topics to sort

== Install

To install this flake from an installation iso, first enter a Nix shell with dependencies:

```sh
$ nix-shell -p git nixUnstable
```

This is required since *git* isn't a hard dependency, and flakes only available in *nixUnstable*.
Then, partition according to the NixOs manual. (TODO: storage module shenanigans).

After that, run the actual installation (assuming that everything is mounted under _/mnt_):

```sh
$ nixos-install --root /mnt --flake github:barsoosayque/nixconfig#station
```

(TODO: why #station ? why github ? local option w/ custom hardware/system setup)

=== Set background

Background management is made with `background` command (which is a shortcut to `setroot --store`). To see available options and usage, consult `man setroot`. In general, you just want to simply set background pictures:

```sh
$ background pictures/wallpapers/left-monitor-picture.png \
             pictures/wallpapers/right-monitor-picture.png
```

Every run of `background` command is saved so it would be restored at the next system start (at `.xinit` execution).