= nixconfig

big wip

== TODO
* [x] Dunst notifications (or something else)  and plug notifications to events
* [x] Transmission and its events
* [x] Alacritty module
* [ ] Unclutter home
* [x] Remove all 'with lib;'
* [ ] Declarative pretty config: colors and background image(s)
* [x] Zsh with simple prompt
* [ ] Audio change notification
* [ ] Pick window & audio change it + notification
* [x] Polybar

== Pile of topics to sort

== Install

To install this flake from an installation iso, first enter a `sudo` mode and then create a Nix shell with dependencies:

```sh
$ sudo -i
$ nix-shell -p git nixVersions.latest
```

This is required since *git* isn't a hard dependency, and flakes only available in latest *nix*.
Then, partition according to the NixOs manual. In this nixconfig, there is an option to create and automatically link directories from `/storage` to `/home/user`,
so it might be usefull to mount `/` to hdd and home directory to ssd.

After that, mount disks and run the actual installation:

```sh
$ mount /dev/disk/by-label/nixos /mnt
$ mount /dev/disk/by-label/boot /mnt/boot
# Replace hostname with the actual host config name from _hosts/_
$ nixos-install --root /mnt --flake .#hostname
````

=== New host

To add a new host, first you need to create a host dir in _hosts/_, and then generate a hadrware config:

```sh
$ mkdir hosts/myhost
$ nixos-generate-config --root /mnt --show-hardware-config > hosts/myhost/hardware.nix
```

Hardware config must be named _hardware.nix_. Then add or copy a `system.nix` file and config a new host system.

=== Set background

Background management is made with `background` command (which is a shortcut to `setroot --store`). To see available options and usage, consult `man setroot`. In general, you just want to simply set background pictures:

```sh
$ background pictures/wallpapers/left-monitor-picture.png \
             pictures/wallpapers/right-monitor-picture.png
```

Every run of `background` command is saved so it would be restored at the next system start (at `.xinit` execution).
