{ config, options, pkgs, lib, ... }:

let
  inherit (lib) mkIf mkOption mkEnableOption types lists attrsets;
  
  cfg = config.modules.x11.xsession;
in
{
  options.modules.x11.xsession = {
    enable = mkEnableOption "xsession";

    videoDrivers = mkOption {
      type = with types; enum ["intel" "nvidia"];
      description = "Video drivers to use. See services.xserver.videoDrivers";
    };
  };

  config = mkIf cfg.enable {
    environment.etc."profile.local".text = ''
      # /etc/profile.local: DO NOT EDIT -- autogenerated
      # just run X
      if [ -z "$DISPLAY" ] && [ $( tty ) == "/dev/tty1" ]; then
        exec startx
      fi
    '';
    environment.sessionVariables = attrsets.optionalAttrs (cfg.videoDrivers == "nvidia") {
      VK_DRIVER_FILES = "${config.hardware.nvidia.package}/share/vulkan/icd.d/nvidia_icd.x86_64.json";
    };

    services.xserver = {
      enable = true;
      videoDrivers = lists.optional (cfg.videoDrivers == "nvidia") "nvidia";
      displayManager.startx.enable = true;
    };

    hardware = {
      nvidia = {
        package = config.boot.kernelPackages.nvidiaPackages.stable;
        modesetting.enable = true;
        powerManagement.enable = false;
        powerManagement.finegrained = false;
        open = false;
      };
      graphics = {
        enable = true;
        extraPackages = with pkgs; lists.optionals (cfg.videoDrivers == "intel") [
          intel-media-driver
          vaapiIntel
          vaapiVdpau
          libvdpau-va-gl
        ];
      };
    };

    nixpkgs.config.packageOverrides = pkgs: {
      vaapiIntel = pkgs.vaapiIntel.override {
        enableHybridCodec = cfg.videoDrivers == "intel";
      };
    };

    system.user.hm.xsession = {
      enable = true;
      scriptPath = ".xinitrc";
      initExtra = "${config.system.events.onStartupScript}";
    };
  };
}
