{ config, options, pkgs, lib, ... }:

let
  inherit (lib) mkIf mkOption mkEnableOption types lists attrsets;
  
  cfg = config.modules.graphics.x11;
in
{
  options.modules.graphics.x11 = {
    enable = mkEnableOption "x11";
  };

  config = mkIf cfg.enable {
    environment.etc."profile".text = ''
      # /etc/profile: DO NOT EDIT -- autogenerated
      # just run X
      if [ -z "$DISPLAY" ] && [ $( tty ) == "/dev/tty1" ]; then
        exec startx
      fi
    '';

    services.xserver = {
      enable = true;
      displayManager.startx.enable = true;
    };

    system.user.hm.xsession = {
      enable = true;
      scriptPath = ".xinitrc";
      initExtra = "${config.system.events.onStartupScript}";
    };

    xdg.portal = {
      enable = true;
      extraPortals = with pkgs; [ pantheon.xdg-desktop-portal-pantheon ];
      xdgOpenUsePortal = true;
      config = {
        common = {
          default = "pantheon";
        };
      };
    };
    programs.dconf.enable = true;
  };
}
