{
  config,
  options,
  pkgs,
  lib,
  ...
}:

let
  inherit (lib)
    mkIf
    mkOption
    mkEnableOption
    types
    lists
    attrsets
    ;

  cfg = config.modules.graphics.x11;

  xclip-file = pkgs.writeShellApplication {
    name = "xclip-file";
    runtimeInputs = [
      pkgs.coreutils
      pkgs.xclip
    ];
    text = ''
      set -euo pipefail

      if [ "$#" -eq 0 ]; then
        echo "Usage: xclip-file-url <file> [...]" >&2
        exit 1
      fi

      for file in "$@"; do
        if [ ! -e "$file" ]; then
          echo "Error: file does not exist: $file" >&2
          exit 1
        fi
        printf 'file://%s\n' "$(realpath "$file")"
      done | xclip -selection clipboard -t text/uri-list

      echo "Copied $# file(s) to clipboard"
    '';
  };
in
{
  options.modules.graphics.x11 = {
    enable = mkEnableOption "x11";
  };

  config = mkIf cfg.enable {
    environment.etc."profile".text = ''
      # /etc/profile: DO NOT EDIT -- autogenerated
      # just run X
      if [ -z "$DISPLAY" ] && [ $( tty ) == "/dev/tty1" ]; then
        exec startx
      fi
    '';

    services.xserver = {
      enable = true;
      displayManager.startx.enable = true;
    };

    environment = {
      systemPackages = [
        pkgs.xclip
        xclip-file
      ];
    };

    system.user.hm.xsession = {
      enable = true;
      scriptPath = ".xinitrc";
      initExtra = "${config.system.events.onStartupScript}";
    };

    # https://github.com/NixOS/nixpkgs/issues/189851#issuecomment-1238907955
    systemd.user.extraConfig = ''
      DefaultEnvironment="PATH=/run/current-system/sw/bin"
    '';
    xdg.portal = {
      enable = true;
      extraPortals = with pkgs; [ xdg-desktop-portal-gtk ];
      xdgOpenUsePortal = true;
      config = {
        common = {
          default = "gtk";
        };
      };
    };
    programs.dconf.enable = true;
  };
}
